// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SmartNutrition.Data;

#nullable disable

namespace SmartNutrition.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509203604_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("SmartNutrition.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Icone")
                        .HasColumnType("TEXT");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icone = "🌅",
                            Libelle = "Petit-déjeuner"
                        },
                        new
                        {
                            Id = 2,
                            Icone = "☀️",
                            Libelle = "Déjeuner"
                        },
                        new
                        {
                            Id = 3,
                            Icone = "🌙",
                            Libelle = "Dîner"
                        },
                        new
                        {
                            Id = 4,
                            Icone = "🍰",
                            Libelle = "Dessert"
                        });
                });

            modelBuilder.Entity("SmartNutrition.Models.Ingredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("CaloriesParUnite")
                        .HasColumnType("REAL");

                    b.Property<double?>("Glucides")
                        .HasColumnType("REAL");

                    b.Property<double?>("Lipides")
                        .HasColumnType("REAL");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Proteines")
                        .HasColumnType("REAL");

                    b.Property<int>("UniteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("UniteId");

                    b.ToTable("Ingredients");
                });

            modelBuilder.Entity("SmartNutrition.Models.Recette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DureePreparation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NbPersonnes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.Property<int>("TypeCuisineId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.HasIndex("TypeCuisineId");

                    b.ToTable("Recettes");
                });

            modelBuilder.Entity("SmartNutrition.Models.RecetteIngredient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IngredientId")
                        .HasColumnType("INTEGER");

                    b.Property<double>("Quantite")
                        .HasColumnType("REAL");

                    b.Property<int>("RecetteId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("IngredientId");

                    b.HasIndex("RecetteId");

                    b.ToTable("RecetteIngredients");
                });

            modelBuilder.Entity("SmartNutrition.Models.TypeCuisine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("TEXT");

                    b.Property<string>("Pays")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("TypesCuisine");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "Tunisienne",
                            Pays = "Tunisie"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "Française",
                            Pays = "France"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "Italienne",
                            Pays = "Italie"
                        },
                        new
                        {
                            Id = 4,
                            Libelle = "Méditerranéenne",
                            Pays = "Méditerranée"
                        });
                });

            modelBuilder.Entity("SmartNutrition.Models.Unite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Symbole")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Unites");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Libelle = "Gramme",
                            Symbole = "g"
                        },
                        new
                        {
                            Id = 2,
                            Libelle = "Kilogramme",
                            Symbole = "kg"
                        },
                        new
                        {
                            Id = 3,
                            Libelle = "Millilitre",
                            Symbole = "ml"
                        },
                        new
                        {
                            Id = 4,
                            Libelle = "Centilitre",
                            Symbole = "cl"
                        },
                        new
                        {
                            Id = 5,
                            Libelle = "Pièce",
                            Symbole = "pcs"
                        },
                        new
                        {
                            Id = 6,
                            Libelle = "Cuillère à soupe",
                            Symbole = "c.s"
                        });
                });

            modelBuilder.Entity("SmartNutrition.Models.Ingredient", b =>
                {
                    b.HasOne("SmartNutrition.Models.Unite", "Unite")
                        .WithMany("Ingredients")
                        .HasForeignKey("UniteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Unite");
                });

            modelBuilder.Entity("SmartNutrition.Models.Recette", b =>
                {
                    b.HasOne("SmartNutrition.Models.Categorie", "Categorie")
                        .WithMany("Recettes")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartNutrition.Models.TypeCuisine", "TypeCuisine")
                        .WithMany("Recettes")
                        .HasForeignKey("TypeCuisineId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Categorie");

                    b.Navigation("TypeCuisine");
                });

            modelBuilder.Entity("SmartNutrition.Models.RecetteIngredient", b =>
                {
                    b.HasOne("SmartNutrition.Models.Ingredient", "Ingredient")
                        .WithMany("RecetteIngredients")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SmartNutrition.Models.Recette", "Recette")
                        .WithMany("RecetteIngredients")
                        .HasForeignKey("RecetteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingredient");

                    b.Navigation("Recette");
                });

            modelBuilder.Entity("SmartNutrition.Models.Categorie", b =>
                {
                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("SmartNutrition.Models.Ingredient", b =>
                {
                    b.Navigation("RecetteIngredients");
                });

            modelBuilder.Entity("SmartNutrition.Models.Recette", b =>
                {
                    b.Navigation("RecetteIngredients");
                });

            modelBuilder.Entity("SmartNutrition.Models.TypeCuisine", b =>
                {
                    b.Navigation("Recettes");
                });

            modelBuilder.Entity("SmartNutrition.Models.Unite", b =>
                {
                    b.Navigation("Ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
